[schema]
file = "./schema.toml"
format = "toml"

[input]
files = "../i18n/**.toml"
format = "toml"
fallback = "../i18n/en.toml"

[output]
dir = "../app/src/main/assets/i18n"
format = "json"
stringFormat = "java-format-string"

[locales]
file = "../i18n/locales.g.json"
format = "json"

[hooks]
files = ["./hooks/kt-sync.js", "./hooks/locales.js"]
